### ISSUE TITLE
Fitting continuum parameters in Peak Editor don't stay unchecked

### ISSUE THREAD

**Issue by kaasknak** [sandialabs/InterSpec#10]
Where to find:
![image](https://user-images.githubusercontent.com/46268724/149354170-1ead1183-450f-4bc3-81a9-016933aa8960.png)

Observed behaviour: After unticking the boxes for fitting parameters (Cont. P0 and Cont. P1) these boxes will automatically become ticked again after a single refit.

Expected behaviour: The boxes remain unticked until they are manually reticked.

On another note. Thank you very much for making and maintaining this wonderful piece of software.

**Comment by wcjohns** [comment]
Thank you for reporting this!

This issue has been fixed.  
I also fixed a few similar consistency-of-behavior type things having to do with this dialog as well.
These changes will all be in the upcoming v1.0.9 release.

This got me to thinking that longer-term, I would also like to remove the "Apply" button and have changes applied as you make them.  But it makes sense to do this after some other planned changes, so it will go on the TODO list for the moment.

And thank you for the kind words.
