### ISSUE TITLE
Minor error in checking GADRAS GAM file version 1

### ISSUE THREAD

**Issue by ahmedmoust** [sandialabs/InterSpec#15]
The if statement for GAM file version 1 check is incorrectly checking the first entry twice instead of the first two entries. The correct statement should be
`if( (fields[0] == "0") && (fields[1] == "0") ){ ... }`
https://github.com/sandialabs/InterSpec/blob/e1d28ce8776c126207e7efa3b2d67eab09001923/src/GadrasGamFileParser.cpp#L60

**Comment by wcjohns** [comment]
Thank you very much for finding and fixing this!
