### ISSUE TITLE
CMakeLists: create data, or symlink data?

### ISSUE THREAD

**Issue by jpbrodsky** [sandialabs/InterSpec#2]
https://github.com/sandialabs/InterSpec/blame/master/CMakeLists.txt#L1184

This line creates the "data" folder in the build directory.

At: https://github.com/sandialabs/InterSpec/blame/master/CMakeLists.txt#L1217

The CMakeLists attempt to create a symlink to the data directory in the source code.

This creates a conflict, since the data directory already exists at the time when a data symlink is supposed to be created.

One resolution would be to move line 1184 down after the symlink is created.

**Comment by wcjohns** [comment]
This hadn't triggered for me, but is clearly and issue - thanks for the for the suggested fix!
