### ISSUE TITLE
Landau skew option in peak editor

### ISSUE THREAD

**Issue by NoahMesserli3065** [sandialabs/InterSpec#22]
Using a small cadmium zinc telluride detector, there is a common effect where the photopeak of the energy spectrum is seriously asymmetric, so that the measured energy spectrum has a “tail” near the low energy region of the photopeak, which is called low-energy tail phenomenon, and this phenomenon becomes more and more significant with the increase of the ray energy. You have already implemented a Landau Skew option in the peak editior, which is great. However, this does not seem to work well if the tail of the photopeak is on the lower energy side, as it is in my case (since the Landau distribution has a tail on the higher energy side of the peak). Is there a way one can use the implemented Landau distribution in InterSpec to fit the assymetric photopeak created by the CdZnTe detector? Or is it possible to slightly adapt the Landau Skew model in order to make the tail go either way (whichever best fits the data)?

**Comment by NoahMesserli3065** [comment]
I just took a closer look at the Landau distribution. If you implemented the following distribution:

$p(x;a,b) = \frac{1}{\pi b} \int_0^\infty e^{-t} \cos\left(t \left( \frac{x-a}{b} \right) + \frac{2t}{\pi} \log\left(\frac{t}{b}\right)\right) dt $, 

the problem could be solved by adding an option of changing the following sign:

$p(x;a,b) = \frac{1}{\pi b} \int_0^\infty e^{-t} \cos\left(t \left( \frac{x-a}{b} \right) - \frac{2t}{\pi} \log\left(\frac{t}{b}\right)\right) dt $.

This would make the tail go the other way. If you could perhaps implement a function that would allow the sign of this Landau distribution to be changed, I would be very grateful. This would allow me to make much better peak fits with my CdZnTe detector. 

Thank you for your reply and Happy Easter!

**Comment by wcjohns** [comment]
Hello,

Thank you for writing about this and opening an issue!

The implemented Landau peak skew stuff is currently not very good :(
Because of this, I haven't touched/used it in quite a few years.
In trying it out in response to this issue, I noticed the peak-drawing code (which has been entirely re-written since I last used landau skew) is not currently taking into account the Landau parameters even (although the underlying fitting code is - but this does you little good without being able to visually check the results).

We are planning some improvements to peak fitting over the next ~6 months, and were already planning on better support of CZT peaks, and so we will also make sure to incorporate this feedback, and your suggested fixes, into the work.

I'll leave this issue open, with the expected improvement time frame being around 6 months or so. Sorry.
  -will

**Comment by NoahMesserli3065** [comment]
Hello Will

Thank you for your quick response and your efforts to improve the software. I am really looking forward to your future implementations. 

All the best 
Noah

**Comment by wcjohns** [comment]
Hi Noah,

Sorry this took a while, but I just merged support for a hand-full of peak-skew models into the primary branch of InterSpec; if you are Windows, the automated [bleeding-edge](https://github.com/sandialabs/InterSpec/releases/tag/bleeding-edge) build should have this, or for other OSs, there will likely be a v1.0.12 release candidate coming up.

In revisiting the Landau skew model, its stableness and definition was sub-par, so it got removed.

However, relevant to you, I put in two, two-sided skew models:

1. A "double-sided" version of the Crystal Ball distribution.  See chapter 6 of http://nrs.harvard.edu/urn-3:HUL.InstRepos:29362185 for its definition.
2. The "ExGaussEx" distribution from https://arxiv.org/abs/1603.08591

I haven't checked that many CZT spectra yet, but for the ones I have, the Double Sided Crystal Ball distribution seems to do a pretty good job fitting peaks that seem to have a good amount of tailing on both sides, and are clearly asymmetric.

You can use the "Peak Editor" to change/fit/manipulate the peak skew fit, or if you right-click on a peak, there is a "Change Skew Type" sub-menu.

If you have any feedback, or the skew models aren't working well for you, please feel free to email InterSpec@sandia.gov.

thanks,
  -will

**Comment by NoahMesserli3065** [comment]
Dear Will

Thank you so much for your time and effort. I will gladly check it out!

Thanks,
Noah
