### ISSUE TITLE
Feature request: Peak colouring in Check Peak Search Results

### ISSUE THREAD

**Issue by tkerby** [sandialabs/InterSpec#27]
When you have a sample with a lot of peaks in the check peak search results, all the peaks are shown in blue. Could the previewed peak that you are choosing be coloured in a different colour to highlight it against the others?

**Comment by wcjohns** [comment]
This is a good suggestion - thank you for it!

I wasn't entirely sure how to then handle which colors would be picked for what, so I instead decreased the alpha value for non-primary peaks; this seems to make it clear which peak is the subject of the row.

Example:
<img width="238" alt="example_peaks" src="https://github.com/sandialabs/InterSpec/assets/9889376/d38715b8-193a-4aa9-87af-6f71ba192198">

(btw, there is a known issue that sometimes there are glitches in drawing these preview peaks, causing erroneous lines, or lines in nonsensical directions - this was a good reminder that I should re-look at this)

thanks,
  -will
