### ISSUE TITLE
Loses photopeaks on orientation change

### ISSUE THREAD

**Issue by Brekel42** [sandialabs/InterSpec#35]
On the latest version of the Android app (1.0.13), the selected reference photopeaks are lost when the phone changes from portrait to landscape mode. 
They are not lost when changing the other way though, from landscape to portrait.

**Comment by wcjohns** [comment]
Keeping the reference photopeak lines showing when you rotate from portrait to landscape does seem quite useful.
I'll add this in before the next version.

There are probably some more things related to rotating the phone, or the new portrait mode, that will be able to be improved as well - ideas are quite welcome.

Thanks for the suggestion @Brekel42!

**Comment by wcjohns** [comment]
This functionality was implemented in ed3a84bf83566e5039066600e6893de06547c1b6.
